### ISSUE TITLE
Api Issue:

### ISSUE THREAD

**Issue by johnmarsh553** [StayWell/StayWell-API-CSharp-Client#1]
How do i execute the given code using Visual Studio. The problem is every project given is a C# class. So i can't make it to "Set to startup project".

**Comment by TimCostantino** [comment]
Hey John, you can setup the startup project by doing the following: 1) Download the latest from GitHub 2) Open the Solution 3) Right-Click on "StayWell.WebExample" 4) Select "Set as StartUp Project"

**Comment by johnmarsh553** [comment]
Thanks Tim, Now its working fine.

**Comment by johnmarsh553** [comment]
Hi Tim,
            I was working on your latest updated code. I've changed the
AppId and AppSecret which I've got from my client. The thing is, On using
DisplayCollections method of Example Controller it was able to fetch only
three collections namely
- Diseases and Conditions Collection
- Tests & Procedures
- Wellness Library

. What about the other collections?  Thanks in Advance.

Regards,
John

**Comment by TimCostantino** [comment]
John,

Please reach out to your account manager at StayWell.  Your license may need to have additional collections added to the license.

Thanks,
Tim

**Comment by johnmarsh553** [comment]
Hi Tim,
            Is there any single REST API Call which returns all the
Contents(with body/Segments) inside a collection. Kindly, let me know.
Thanks in Advance.

Regards,
John

**Comment by TimCostantino** [comment]
John, that method doesn't currently exist.  Could you help me understand your use-case?  That will help me better prioritize the request.

**Comment by johnmarsh553** [comment]
Thanks for Reply Tim. I'm done with my requirement. Thanks a lot.
